name: lein-project-reader tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: lein deps

    ## Useful for debugging problems - CI will pause and provide an ssh connection
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: Run tests
      run: lein test
